<?php

/**
 * Order Comment Extension for Magento 2
 *
 * @author     Volodymyr Konstanchuk http://konstanchuk.com
 * @copyright  Copyright (c) 2017 The authors
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/** @var \Konstanchuk\OrderComment\Block\Adminhtml\Order\View\Comment $block */
$comment = $block->getCustomerOrderComment();
if ($comment):
    ?>
    <section class="admin__page-section-item order-comment">
        <div class="admin__page-section-item-title">
            <span class="title">
                <?php /* @escapeNotVerified */
                echo __('Customer Comment') ?>
            </span>
        </div>
        <div class="admin__page-section-item-content">
            <div class="order-comment-text">
                <?php echo $block->escapeHtml($comment); ?>
            </div>
        </div>
    </section>
    <script type="text/x-magento-init">
{
    ".order-comment-text": {
        "Konstanchuk_OrderComment/js/show-more-text": {}
    }
}


    </script>
<?php endif; ?>